version: '3'
services:
  discounts:
    environment:
      - FLASK_APP=discounts.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    image: "ddtraining/discounts-service:latest"
    command: flask run --port=5001 --host=0.0.0.0
    ports:
      - "5001:5001"
    depends_on:
      - db
  frontend:
    environment:
      - DB_USERNAME
      - DB_PASSWORD
    image: "ddtraining/ecommerce-frontend-broken:latest"
    command: sh docker-entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - "../store-frontend-broken-instrumented/store-frontend:/spree/store-frontend"
    depends_on:
      - db
      - discounts
      - advertisements
  advertisements:
    environment:
      - FLASK_APP=ads.py
      - FLASK_DEBUG=1
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    image: "ddtraining/advertisements-service:latest"
    command: flask run --port=5002 --host=0.0.0.0
    ports:
      - "5002:5002"
    volumes:
      - "../ads-service:/app"
    depends_on:
      - bling-bling
      - db
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
  bling-bling:
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    image: "ursuladd/bling-bling:latest"
    command: flask run --port=5003 --host=0.0.0.0
    ports:
      - "5003:5003"
