apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecommerce
    service: advertisements
    tags.datadoghq.com/env: development
    tags.datadoghq.com/service: advertisements
    tags.datadoghq.com/version: "v1.0"
  name: advertisements
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      service: advertisements
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        ad.datadoghq.com/advertisements.logs: '[{"source":"python","service":"advertisements"}]'
      labels:
        app: ecommerce
        service: advertisements
        tags.datadoghq.com/env: development
        tags.datadoghq.com/service: advertisements
        tags.datadoghq.com/version: "v1.0"
    spec:
      containers:
      - args:
        - flask
        - run
        - --port=5002
        - --host=0.0.0.0
        command:
        - ddtrace-run
        env:
        - name: FLASK_APP
          value: ads.py
        - name: FLASK_DEBUG
          value: "1"
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              key: name
              name: storedog-advertisements-db
        - name: POSTGRES_SCHEMA
          valueFrom:
            secretKeyRef:
              key: schema
              name: storedog-advertisements-db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: pw
              name: storedog-advertisements-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: usr
              name: storedog-advertisements-db
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: storedog-advertisements-db
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_ANALYTICS_ENABLED
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_SERVICE_MAPPING
          value: "postgres:advertisements-postgres"
        image: econocombrasil/advertisements-service:v1.0
        imagePullPolicy: Always
        name: advertisements
        ports:
        - containerPort: 5002
          protocol: TCP
        resources: {}


---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: ecommerce
    service: advertisements
    tags.datadoghq.com/env: development
    tags.datadoghq.com/service: advertisements
  name: advertisements
spec:
  ports:
  - port: 5002
    protocol: TCP
    targetPort: 5002
  selector:
    app: ecommerce
    service: advertisements
  sessionAffinity: None
  type: ClusterIP
