apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ecommerce
    service: discounts
    tags.datadoghq.com/env: development
    tags.datadoghq.com/service: discounts
    tags.datadoghq.com/version: "v1.0"
  name: discounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      service: discounts
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        ad.datadoghq.com/discounts.logs: '[{"source":"python","service":"discounts"}]'
      labels:
        app: ecommerce
        service: discounts
        tags.datadoghq.com/env: development
        tags.datadoghq.com/service: discounts
        tags.datadoghq.com/version: "v1.0"
    spec:
      containers:
      - args:
        - flask
        - run
        - --port=5001
        - --host=0.0.0.0
        command:
        - ddtrace-run
        env:
        - name: FLASK_APP
          value: discounts.py
        - name: FLASK_DEBUG
          value: "1"
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              key: name
              name: storedog-discounts-db
        - name: POSTGRES_SCHEMA
          valueFrom:
            secretKeyRef:
              key: schema
              name: storedog-discounts-db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: pw
              name: storedog-discounts-db
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: usr
              name: storedog-discounts-db
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              key: host
              name: storedog-discounts-db
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: DD_ANALYTICS_ENABLED
          value: "true"
        - name: DD_PROFILING_ENABLED
          value: "true"
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']
        - name: DD_SERVICE_MAPPING
          value: "postgres:discounts-postgres"
        image: econocombrasil/discounts-service:v1.0
        imagePullPolicy: Always
        name: discounts
        ports:
        - containerPort: 5001
          protocol: TCP
        resources: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ecommerce
    service: discounts
    tags.datadoghq.com/env: development
    tags.datadoghq.com/service: discounts
  name: discounts
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: ecommerce
    service: discounts
  sessionAffinity: None
  type: ClusterIP
