# Docker compose file which uses build context plus mounted volumes for easier local development
# Note: storefront-fixed cannot use the build context because the .patch files are located in a parent directory of the Dockerfile
version: '3'
services:
  nginx:
    restart: always
    image: nginx
    ports:
      - "8080:80"
    labels:
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "nginx"}]'