name: Discounts Service (Fixed) - Test and Build

on:
  push:
    branches: [ main ]
    paths:
      - discounts-service-fixed/**

defaults:
  run:
    working-directory: discounts-service-fixed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to ECR
      id: login-ecr
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./discounts-service-fixed
        platforms: linux/amd64
        push: true
        tags: |
          ddtraining/discounts-service-fixed:latest
          public.ecr.aws/b1o7r7e0/ddtraining/discounts-service-fixed:latest

