name: Synthetics Test

on:
  push:
    branches:
      - ccole/synth-ci

jobs:   

  synthetics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start app
        run: |
          docker-compose -f deploy/docker-compose/docker-compose.synthetics-ci-cd.yml up -d
          docker ps -a

      - name: Check Runner Info
        run: |
          cat /etc/hosts
          curl localhost:8080 
          curl -I 127.0.0.1:8080 

      - name: Run Datadog Synthetics tests
        uses: DataDog/synthetics-ci-github-action@v0.3.0
        with:
          api_key: ${{secrets.DD_API_KEY}}
          app_key: ${{secrets.DD_APP_KEY}}
