name: Synthetics Test

on:
  push:
    branches:
      - ccole/synth-ci

jobs:   

  synthetics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start app
        run: DD_API_KEY=${{secrets.DD_API_KEY}} make synthetics-ci-cd-start

      - name: Check Docker
        run: |
          curl -I http://nginx:80

      - name: Check Runner Info
        run: |
          cat /etc/hosts
          ping 127.0.0.1
