name: Synthetics Test

on:
  push:
    branches:
      - ccole/synth-tunnel

jobs:   

  synthetics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start app
        run: DD_API_KEY=${{secrets.DD_API_KEY}} make local-baseline-start

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Ping IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          ping ${{ steps.ip.outputs.ipv4 }}
          curl -I ${{ steps.ip.outputs.ipv4 }}