name: Synthetics Test

on:
  push:
    branches:
      - ccole/synth-tunnel

jobs:   

  synthetics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start app
        run: DD_API_KEY=${{secrets.DD_API_KEY}} make local-baseline-start
      - name: Sleep
        run: sleep 10
      - name: Run Datadog Synthetics tests
        uses: DataDog/synthetics-ci-github-action@v0.3.0
        with:
          api_key: ${{secrets.DD_API_KEY}}
          app_key: ${{secrets.DD_APP_KEY}}