name: Synthetics Test

on:
  push:
    branches:
      - ccole/synth-ci

jobs:   

  synthetics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Start app
        run: |
          docker run hello-world
          docker ps -a

      - name: Check Runner Info
        run: |
          cat /etc/hosts
          ping 127.0.0.1
