name: Synthetics Test

on:
  push:
    branches:
      - ccole/synth-ci

jobs:   

  synthetics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Pull agent
        run: docker pull datadog/agent:7.35.0

      - name: Pull discounts
        run: docker pull public.ecr.aws/x2b9z2t7/ddtraining/discounts-fixed:latest

      - name: Pull frontend
        run: docker pull public.ecr.aws/x2b9z2t7/ddtraining/storefront-fixed:latest

      - name: Pull ads
        run: docker pull public.ecr.aws/x2b9z2t7/ddtraining/advertisements-fixed:latest

      - name: Pull nginx
        run: docker pull public.ecr.aws/x2b9z2t7/ddtraining/nginx:latest

      - name: Pull db
        run: docker pull postgres:11-alpine

      - name: Pull attackbox
        run: docker pull public.ecr.aws/x2b9z2t7/ddtraining/attackbox:latest

      - name: Start app
        run: |
          DD_API_KEY=${{secrets.DD_API_KEY}} make latest-start
          docker ps -a

      - name: Check localhost
        run: |
          curl -I http://localhost:80

      - name: Run Datadog Synthetics tests
        uses: DataDog/synthetics-ci-github-action@v0.3.0
        with:
          api_key: ${{secrets.DD_API_KEY}}
          app_key: ${{secrets.DD_APP_KEY}}
