name: Synthetics Test

on:
  push:
    branches:
      - ccole/synth-ci

jobs:   

  synthetics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check Runner Info
        run: |
          cat /etc/hosts
